/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as crons from "../crons.js";
import type * as http from "../http.js";
import type * as stripe_events from "../stripe/events.js";
import type * as stripe_index from "../stripe/index.js";
import type * as stripe_webhook_action from "../stripe/webhook/action.js";
import type * as stripe_webhook_process from "../stripe/webhook/process.js";
import type * as stripe_webhook_verify from "../stripe/webhook/verify.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  crons: typeof crons;
  http: typeof http;
  "stripe/events": typeof stripe_events;
  "stripe/index": typeof stripe_index;
  "stripe/webhook/action": typeof stripe_webhook_action;
  "stripe/webhook/process": typeof stripe_webhook_process;
  "stripe/webhook/verify": typeof stripe_webhook_verify;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
